import { Copy, Download } from 'lucide-react'
import { lazy, Suspense } from 'react'
import toast from 'react-hot-toast'

import {
  originalPolicy as demoOriginalPolicy,
  remediatedPolicy as demoRemediatedPolicy,
} from '../../data/mockSecurityData'

import { getAnalysis } from '../../data/analysisData'

import Button from '../Common/Button'

const JsonViewer = lazy(() => import('./JsonViewer'))

const codeFallback = (
  <div className="flex min-h-72 items-center justify-center text-sm text-slate-400">
    Loading policy viewer...
  </div>
)

export default function PolicyComparison() {
  const analysis = getAnalysis()

  const originalPolicy = analysis?.policy
    ? JSON.stringify(analysis.policy, null, 2)
    : demoOriginalPolicy

  const remediatedPolicy = analysis?.secure_policy
    ? JSON.stringify(analysis.secure_policy, null, 2)
    : demoRemediatedPolicy

  const copy = async () => {
    await navigator.clipboard.writeText(remediatedPolicy)
    toast.success('Remediated policy copied')
  }

  const download = () => {
    const blob = new Blob([remediatedPolicy], {
      type: 'application/json',
    })

    const url = URL.createObjectURL(blob)

    const anchor = document.createElement('a')

    anchor.href = url
    anchor.download = 's3-policy-remediated.json'
    anchor.click()

    URL.revokeObjectURL(url)

    toast.success('JSON download started')
  }

  return (
    <section className="rounded-3xl border border-white/10 bg-[#121827]/55 p-6 backdrop-blur-xl shadow-xl">

      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center">

        <div>

          <h2 className="text-lg font-semibold text-white">
            Policy Comparison
          </h2>

          <p className="mt-1 text-sm text-slate-300">
            Compare the uploaded policy with the AI-recommended secure version.
          </p>

        </div>

        <div className="flex flex-wrap gap-2">

          <Button
            variant="secondary"
            onClick={copy}
          >
            <Copy size={15} />
            Copy Policy
          </Button>

          <Button
            onClick={download}
          >
            <Download size={15} />
            Download JSON
          </Button>

        </div>

      </div>

      <div className="mt-6 grid gap-5 lg:grid-cols-2">

        {/* Original */}

        <div className="overflow-hidden rounded-2xl border border-rose-400/15 bg-slate-950/35 backdrop-blur-md">

          <div className="border-b border-rose-400/10 bg-rose-400/5 px-5 py-4">

            <p className="font-semibold text-rose-200">
              Original Policy
            </p>

            <p className="mt-1 text-xs text-rose-100/70">
              Uploaded configuration
            </p>

          </div>

          <Suspense fallback={codeFallback}>
            <JsonViewer code={originalPolicy} />
          </Suspense>

        </div>

        {/* Remediated */}

        <div className="overflow-hidden rounded-2xl border border-emerald-400/15 bg-slate-950/35 backdrop-blur-md">

          <div className="border-b border-emerald-400/10 bg-emerald-400/5 px-5 py-4">

            <p className="font-semibold text-emerald-200">
              AI Remediated Policy
            </p>

            <p className="mt-1 text-xs text-emerald-100/70">
              Secure version generated by AI
            </p>

          </div>

          <Suspense fallback={codeFallback}>
            <JsonViewer code={remediatedPolicy} />
          </Suspense>

        </div>

      </div>

    </section>
  )
}